# Generated by Django 5.2.8 on 2025-11-29 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title or description', max_length=200)),
                ('due_date', models.DateField(help_text='When the task is due')),
                ('estimated_hours', models.FloatField(help_text='Estimated hours to complete the task', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('importance', models.IntegerField(help_text='Importance level from 1 (low) to 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs that this task depends on')),
                ('priority_score', models.FloatField(blank=True, help_text='Calculated priority score (higher = more urgent)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority_score', 'due_date'],
            },
        ),
    ]
